// <auto-generated />
namespace Senai.Chamados.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class atualzando_chamado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualzando_chamado));
        
        string IMigrationMetadata.Id
        {
            get { return "201807122210171_atualzando_chamado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
